site_name: Sebastian Sukstorf
site_url: https://github.com/sebastiansukstorf/mkdocs.git
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.footnote.tooltips
  language: de
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sebastian-sukstorf/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sukstorf
    - icon: material/email
      link: mailto:info@sebastian.sukstorf.de  


markdown_extensions:
  - admonition
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
  - tables

copyright: |
  &copy; 2024 <a href="https://github.com/sebastiansukstorf/mkdocs.git"  target="_blank" rel="noopener">Sebastian Sukstorf</a>